#! /usr/bin/bash


if [ $# -ne 3 ]
then
	echo "Usage: $0 <start> <end> <file>"
	exit 1
fi

start=$1
end=$2
file=$3

if [ -f $file ]
then
	sed -n "$start, $end p" $file
else
	echo "$file is not a file"
fi

