#! /usr/bin/bash

if [ $# -eq 0 ];
then
	echo "Usage: $0 [file1 ... fileN]"
	exit 1
fi


for file in "$@"
do
	if [ -f $file  ];
	then
		cat $file | tr "[:lower:]" "[:upper:]" > /tmp/tmpupper
		cat /tmp/tmpupper > $file
	fi
done
